### PR TITLE
Drop support for node v10

### PR DESCRIPTION
**Pull request by hjdivad**

### CODE REVIEW

**Comment by hjdivad** [comment]
@rwjblue LMK if you see any reason not to merge + release 2.0.0

**Comment by hjdivad** [comment]
@rwjblue you might need to be the one to update protected branches.

**Review by scalvert — APPROVED** [review]

**Comment by scalvert** [comment]
Unsure why this is trying to run the `10.x` scenario, when it's been removed.

**Comment by hjdivad** [comment]
@scalvert it's because the repo has it in protected branches. Protected branches are good, but this specific scenario is one where they kinda get in the way a bit.

**Review by rwjblue — APPROVED** [review]

**Pull request merged**
