### PR TITLE
Add typescript types

### PR DESCRIPTION
**Pull request by antonk52**
Hi and thank you for your work!

It would be great if this package could include typescript definitions which typescript and/or vscode users can leverage.

### CODE REVIEW

**Comment by hjdivad** [comment]
@rwjblue see if i missed anything then merge away


@antonk52 thank you very much for the contribution!  This is wonderful

**Comment by antonk52** [comment]
~~These's one thing I missed, it is to include index.d.ts in files field in package.json so the types are published to npm alongside with index.js. I will update the PR shortly.~~
I see you've corrected that already. Thank you!

**Review by rwjblue — APPROVED** [review]

**Comment by antonk52** [comment]
@hjdivad  @rwjblue Can I kindly ask for a new npm release that includes these changes? Please 😅

**Comment by hjdivad** [comment]
@antonk52 released as 2.1.0

**Pull request merged**
